name: ukubiku
description: 'Aluguer e Outros Serviços Imobiliários.'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.3.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
  table_calendar: ^3.0.6
  http: ^0.13.4
  shared_preferences: ^2.0.15
  json_annotation: ^4.6.0
  barcode: ^2.2.3
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
      - assets/images/